function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 8; // obj_player
	global.__objectDepths[1] = 11; // obj_player_warp
	global.__objectDepths[2] = 0; // obj_light
	global.__objectDepths[3] = 0; // obj_light_npc
	global.__objectDepths[4] = 0; // obj_light_static
	global.__objectDepths[5] = 0; // obj_light_disco
	global.__objectDepths[6] = 0; // obj_lightparent
	global.__objectDepths[7] = -9; // obj_lightcontrol
	global.__objectDepths[8] = 8; // obj_checkpoint
	global.__objectDepths[9] = 0; // obj_checkpoint_tape
	global.__objectDepths[10] = 11; // obj_goal_gate
	global.__objectDepths[11] = 8; // obj_orb
	global.__objectDepths[12] = 9; // obj_keyhole
	global.__objectDepths[13] = -7; // obj_rainmaker
	global.__objectDepths[14] = 0; // obj_snowmaker
	global.__objectDepths[15] = -7; // obj_tilehider
	global.__objectDepths[16] = 0; // obj_autoscroll
	global.__objectDepths[17] = 0; // obj_bganimator
	global.__objectDepths[18] = 1000000; // obj_levelcontrol
	global.__objectDepths[19] = 0; // obj_guessblock_manager
	global.__objectDepths[20] = -2; // obj_tilemanager
	global.__objectDepths[21] = -2; // obj_tilemanager_fall
	global.__objectDepths[22] = 0; // obj_tilesolid
	global.__objectDepths[23] = 0; // obj_tilesemisolid
	global.__objectDepths[24] = 0; // obj_tilehurt
	global.__objectDepths[25] = -1; // obj_solid
	global.__objectDepths[26] = -1; // obj_semisolid
	global.__objectDepths[27] = 10; // obj_climb
	global.__objectDepths[28] = 10; // obj_climb_net
	global.__objectDepths[29] = 10; // obj_swim
	global.__objectDepths[30] = -1; // obj_ceiling_slope_r
	global.__objectDepths[31] = -1; // obj_ceiling_slope_l
	global.__objectDepths[32] = -1; // obj_ceiling_slope_steep_r
	global.__objectDepths[33] = -1; // obj_ceiling_slope_steep_l
	global.__objectDepths[34] = -1; // obj_slope_r
	global.__objectDepths[35] = -1; // obj_slope_l
	global.__objectDepths[36] = -1; // obj_slope_wide_r
	global.__objectDepths[37] = -1; // obj_slope_wide_l
	global.__objectDepths[38] = -1; // obj_slope_steep_r
	global.__objectDepths[39] = -1; // obj_slope_steep_l
	global.__objectDepths[40] = -1; // obj_slope_steeper_r
	global.__objectDepths[41] = -1; // obj_slope_steeper_l
	global.__objectDepths[42] = -1; // obj_slope_trunk_r
	global.__objectDepths[43] = -1; // obj_slope_trunk_l
	global.__objectDepths[44] = -1; // obj_slippery
	global.__objectDepths[45] = -1; // obj_slippery_slope_r
	global.__objectDepths[46] = -1; // obj_slippery_slope_l
	global.__objectDepths[47] = -1; // obj_slippery_slope_steep_r
	global.__objectDepths[48] = -1; // obj_slippery_slope_steep_l
	global.__objectDepths[49] = -1; // obj_hurtblock
	global.__objectDepths[50] = -1; // obj_hurtblock_lethal
	global.__objectDepths[51] = 8; // obj_block_mario
	global.__objectDepths[52] = 8; // obj_block_luigi
	global.__objectDepths[53] = 8; // obj_block_toad
	global.__objectDepths[54] = 8; // obj_block_peach
	global.__objectDepths[55] = 0; // obj_area_big_y
	global.__objectDepths[56] = 0; // obj_area_big_g
	global.__objectDepths[57] = 0; // obj_area_big_r
	global.__objectDepths[58] = 0; // obj_area_big_b
	global.__objectDepths[59] = 0; // obj_area_y
	global.__objectDepths[60] = 0; // obj_area_g
	global.__objectDepths[61] = 0; // obj_area_r
	global.__objectDepths[62] = 0; // obj_area_b
	global.__objectDepths[63] = 8; // obj_qblock_big
	global.__objectDepths[64] = 8; // obj_qblock_hidden
	global.__objectDepths[65] = 8; // obj_qblock
	global.__objectDepths[66] = -1; // obj_qblock_winged
	global.__objectDepths[67] = 8; // obj_emptyblock
	global.__objectDepths[68] = 8; // obj_brick_big
	global.__objectDepths[69] = 8; // obj_brick_flip_big
	global.__objectDepths[70] = 8; // obj_brick
	global.__objectDepths[71] = 8; // obj_brick_flip
	global.__objectDepths[72] = 8; // obj_brick_throw
	global.__objectDepths[73] = 8; // obj_brick_fragile
	global.__objectDepths[74] = 8; // obj_brick_crystal
	global.__objectDepths[75] = 8; // obj_brick_stone
	global.__objectDepths[76] = 8; // obj_msgblock
	global.__objectDepths[77] = 8; // obj_noteblock
	global.__objectDepths[78] = 8; // obj_noteblock_hidden
	global.__objectDepths[79] = 8; // obj_noteblock_diagonal_r
	global.__objectDepths[80] = 8; // obj_noteblock_diagonal_l
	global.__objectDepths[81] = 8; // obj_quaverblock
	global.__objectDepths[82] = 8; // obj_playerblock
	global.__objectDepths[83] = 8; // obj_woodblock
	global.__objectDepths[84] = 8; // obj_yblock
	global.__objectDepths[85] = 9; // obj_iceblock
	global.__objectDepths[86] = 9; // obj_iceblock_coin
	global.__objectDepths[87] = 9; // obj_iceblock_muncher
	global.__objectDepths[88] = 8; // obj_viewblock
	global.__objectDepths[89] = 0; // obj_powblock
	global.__objectDepths[90] = 8; // obj_lightblock
	global.__objectDepths[91] = 8; // obj_lightblock_disco
	global.__objectDepths[92] = 8; // obj_onoffblock
	global.__objectDepths[93] = 8; // obj_onoffplatform_red
	global.__objectDepths[94] = 8; // obj_onoffplatform_blue
	global.__objectDepths[95] = 8; // obj_starblock
	global.__objectDepths[96] = 8; // obj_conveyor
	global.__objectDepths[97] = -1; // obj_escalator_r
	global.__objectDepths[98] = -1; // obj_escalator_l
	global.__objectDepths[99] = -1; // obj_escalator_down_r
	global.__objectDepths[100] = -1; // obj_escalator_down_l
	global.__objectDepths[101] = 9; // obj_escalator_joint
	global.__objectDepths[102] = 10; // obj_track_dia_r_on
	global.__objectDepths[103] = 10; // obj_track_dia_r_off
	global.__objectDepths[104] = 10; // obj_track_dia_l_on
	global.__objectDepths[105] = 10; // obj_track_dia_l_off
	global.__objectDepths[106] = -2; // obj_track_modifier
	global.__objectDepths[107] = 10; // obj_track_limit
	global.__objectDepths[108] = 10; // obj_track_h
	global.__objectDepths[109] = 10; // obj_track_v
	global.__objectDepths[110] = 10; // obj_track_dia_r
	global.__objectDepths[111] = 10; // obj_track_dia_l
	global.__objectDepths[112] = 10; // obj_track_circle
	global.__objectDepths[113] = 10; // obj_track_circle_2x
	global.__objectDepths[114] = -1; // obj_platform
	global.__objectDepths[115] = -1; // obj_platform_path
	global.__objectDepths[116] = -1; // obj_platform_falling
	global.__objectDepths[117] = -1; // obj_platform_pulley
	global.__objectDepths[118] = -1; // obj_platform_seesaw
	global.__objectDepths[119] = -1; // obj_platform_island
	global.__objectDepths[120] = -1; // obj_platform_crate
	global.__objectDepths[121] = 12; // obj_platform_ferris
	global.__objectDepths[122] = -1; // obj_platform_yoshi
	global.__objectDepths[123] = -1; // obj_platform_track
	global.__objectDepths[124] = -1; // obj_platform_track_blue
	global.__objectDepths[125] = 1; // obj_platform_accordion_h
	global.__objectDepths[126] = 1; // obj_platform_accordion_v
	global.__objectDepths[127] = 1; // obj_platform_accordion_hv
	global.__objectDepths[128] = -1; // obj_platform_accordian_diag
	global.__objectDepths[129] = -1; // obj_platform_slope_r
	global.__objectDepths[130] = -1; // obj_platform_slope_l
	global.__objectDepths[131] = -1; // obj_platform_timed
	global.__objectDepths[132] = -1; // obj_platform_arrow
	global.__objectDepths[133] = -1; // obj_platform_arrow_l
	global.__objectDepths[134] = -1; // obj_platform_arrow_r
	global.__objectDepths[135] = 10; // obj_movingpipe
	global.__objectDepths[136] = -1; // obj_movingrope
	global.__objectDepths[137] = -1; // obj_movingsaw
	global.__objectDepths[138] = -1; // obj_movingseesaw
	global.__objectDepths[139] = 10; // obj_skullraft
	global.__objectDepths[140] = -1; // obj_donut
	global.__objectDepths[141] = -1; // obj_donut_triple
	global.__objectDepths[142] = -1; // obj_donut_red
	global.__objectDepths[143] = -1; // obj_donut_red_triple
	global.__objectDepths[144] = -1; // obj_donut_ice
	global.__objectDepths[145] = -1; // obj_donut_ice_triple
	global.__objectDepths[146] = -1; // obj_boltlift
	global.__objectDepths[147] = -1; // obj_blocktrain
	global.__objectDepths[148] = -2; // obj_pswitch
	global.__objectDepths[149] = -2; // obj_gswitch
	global.__objectDepths[150] = -2; // obj_trampoline
	global.__objectDepths[151] = -2; // obj_trampoline_timed
	global.__objectDepths[152] = -2; // obj_powblock_blue
	global.__objectDepths[153] = 8; // obj_pblock_on
	global.__objectDepths[154] = 8; // obj_pblock_off
	global.__objectDepths[155] = -2; // obj_walltrampoline
	global.__objectDepths[156] = 9; // obj_walltriangle_r
	global.__objectDepths[157] = 9; // obj_walltriangle_l
	global.__objectDepths[158] = -1; // obj_glowblock
	global.__objectDepths[159] = -2; // obj_crate
	global.__objectDepths[160] = 8; // obj_spikeblock
	global.__objectDepths[161] = 8; // obj_spikeblock_g
	global.__objectDepths[162] = 8; // obj_spikeblock_red
	global.__objectDepths[163] = 8; // obj_spikeblock_blue
	global.__objectDepths[164] = 8; // obj_beepblock_red
	global.__objectDepths[165] = 8; // obj_beepblock_blue
	global.__objectDepths[166] = 9; // obj_boostpanel
	global.__objectDepths[167] = 9; // obj_bombblock
	global.__objectDepths[168] = 9; // obj_deathblock
	global.__objectDepths[169] = 8; // obj_floodblock
	global.__objectDepths[170] = 8; // obj_floodblock_reset
	global.__objectDepths[171] = 8; // obj_icicle
	global.__objectDepths[172] = -1; // obj_icicle_static
	global.__objectDepths[173] = -2; // obj_detonator
	global.__objectDepths[174] = 12; // obj_beanstalk_vine
	global.__objectDepths[175] = -2; // obj_lakitucloud
	global.__objectDepths[176] = 9; // obj_spiketrap
	global.__objectDepths[177] = 0; // obj_bumper
	global.__objectDepths[178] = -1; // obj_key
	global.__objectDepths[179] = 8; // obj_coin
	global.__objectDepths[180] = 8; // obj_coin_p
	global.__objectDepths[181] = 8; // obj_coin_5
	global.__objectDepths[182] = 8; // obj_coin_10
	global.__objectDepths[183] = 8; // obj_coin_ace
	global.__objectDepths[184] = 8; // obj_coin_outline
	global.__objectDepths[185] = -2; // obj_mushroom
	global.__objectDepths[186] = 15; // obj_mushroom_h
	global.__objectDepths[187] = -2; // obj_fireflower
	global.__objectDepths[188] = -2; // obj_feather
	global.__objectDepths[189] = -2; // obj_iceflower
	global.__objectDepths[190] = -2; // obj_star
	global.__objectDepths[191] = -2; // obj_1up
	global.__objectDepths[192] = -1; // obj_1up_h1
	global.__objectDepths[193] = -1; // obj_1up_h2
	global.__objectDepths[194] = -1; // obj_1up_h3
	global.__objectDepths[195] = -1; // obj_1up_h4
	global.__objectDepths[196] = -2; // obj_poison
	global.__objectDepths[197] = -2; // obj_watermelon_fire
	global.__objectDepths[198] = -2; // obj_watermelon_ice
	global.__objectDepths[199] = -2; // obj_watermelon_bomb
	global.__objectDepths[200] = 8; // obj_3upmoon
	global.__objectDepths[201] = -1; // obj_twister
	global.__objectDepths[202] = -1; // obj_goomba_hefty
	global.__objectDepths[203] = -1; // obj_goomba_big
	global.__objectDepths[204] = -1; // obj_goomba
	global.__objectDepths[205] = -1; // obj_paragoomba
	global.__objectDepths[206] = -1; // obj_paragoomba_red
	global.__objectDepths[207] = -1; // obj_galoomba
	global.__objectDepths[208] = -1; // obj_galoomba_parachute
	global.__objectDepths[209] = -1; // obj_paragaloomba
	global.__objectDepths[210] = -1; // obj_galoomba_red
	global.__objectDepths[211] = -1; // obj_goombud
	global.__objectDepths[212] = -1; // obj_supergoomba
	global.__objectDepths[213] = -1; // obj_trolloomba
	global.__objectDepths[214] = -1; // obj_bigkoopa
	global.__objectDepths[215] = -1; // obj_bigparakoopa
	global.__objectDepths[216] = -1; // obj_bigparakoopa_super
	global.__objectDepths[217] = -1; // obj_bigparakoopa_fly
	global.__objectDepths[218] = -1; // obj_bigbeachkoopa
	global.__objectDepths[219] = -1; // obj_classickoopa
	global.__objectDepths[220] = -1; // obj_classicparakoopa
	global.__objectDepths[221] = -1; // obj_classicparakoopa_fly
	global.__objectDepths[222] = -2; // obj_superkoopa_green
	global.__objectDepths[223] = -1; // obj_koopa
	global.__objectDepths[224] = -1; // obj_parakoopa
	global.__objectDepths[225] = -1; // obj_parakoopa_super
	global.__objectDepths[226] = -1; // obj_parakoopa_fly
	global.__objectDepths[227] = -1; // obj_beachkoopa
	global.__objectDepths[228] = -1; // obj_bigkoopa_red
	global.__objectDepths[229] = -1; // obj_bigbeachkoopa_red
	global.__objectDepths[230] = -1; // obj_classickoopa_red
	global.__objectDepths[231] = -1; // obj_classicparakoopa_red
	global.__objectDepths[232] = -1; // obj_classicparakoopa_red_hor
	global.__objectDepths[233] = 0; // obj_superkoopa_red
	global.__objectDepths[234] = -1; // obj_koopa_red
	global.__objectDepths[235] = -1; // obj_parakoopa_red
	global.__objectDepths[236] = -1; // obj_parakoopa_red_hor
	global.__objectDepths[237] = -1; // obj_beachkoopa_red
	global.__objectDepths[238] = -1; // obj_superkoopa
	global.__objectDepths[239] = -1; // obj_koopa_blue
	global.__objectDepths[240] = -1; // obj_parakoopa_blue
	global.__objectDepths[241] = -1; // obj_beachkoopa_blue
	global.__objectDepths[242] = -1; // obj_koopa_yellow
	global.__objectDepths[243] = -1; // obj_parakoopa_yellow
	global.__objectDepths[244] = -2; // obj_parakoopa_yellow_wave
	global.__objectDepths[245] = -1; // obj_beachkoopa_yellow
	global.__objectDepths[246] = -2; // obj_shell
	global.__objectDepths[247] = -1; // obj_shell_kamikaze
	global.__objectDepths[248] = -1; // obj_hammerbro
	global.__objectDepths[249] = -1; // obj_boomerangbro
	global.__objectDepths[250] = -1; // obj_firebro
	global.__objectDepths[251] = -1; // obj_sledgebro
	global.__objectDepths[252] = -1; // obj_afhb
	global.__objectDepths[253] = -1; // obj_sumobro
	global.__objectDepths[254] = -1; // obj_rex
	global.__objectDepths[255] = -1; // obj_rex_red
	global.__objectDepths[256] = -1; // obj_charginchuck
	global.__objectDepths[257] = -1; // obj_clappinchuck
	global.__objectDepths[258] = -1; // obj_confusedchuck
	global.__objectDepths[259] = -1; // obj_bouncinchuck
	global.__objectDepths[260] = -1; // obj_digginchuck
	global.__objectDepths[261] = -1; // obj_passinchuck
	global.__objectDepths[262] = -1; // obj_splittinchuck
	global.__objectDepths[263] = -1; // obj_whistlinchuck
	global.__objectDepths[264] = -1; // obj_dinotorch
	global.__objectDepths[265] = -1; // obj_dinorhino
	global.__objectDepths[266] = -1; // obj_spike
	global.__objectDepths[267] = -1; // obj_buzzybeetle
	global.__objectDepths[268] = -1; // obj_buzzybeetle_ceiling
	global.__objectDepths[269] = -1; // obj_spiny
	global.__objectDepths[270] = -1; // obj_spiny_alt
	global.__objectDepths[271] = -1; // obj_spiny_ceiling
	global.__objectDepths[272] = -2; // obj_piranhacus
	global.__objectDepths[273] = -2; // obj_longpiranhacus
	global.__objectDepths[274] = -2; // obj_piranhaplant
	global.__objectDepths[275] = -2; // obj_piranhaplant_long
	global.__objectDepths[276] = -2; // obj_piranhaplant_long_down
	global.__objectDepths[277] = -2; // obj_fireplant
	global.__objectDepths[278] = -2; // obj_fireplant_long
	global.__objectDepths[279] = -2; // obj_fireplant_long_down
	global.__objectDepths[280] = -2; // obj_jumpplant
	global.__objectDepths[281] = -1; // obj_ptooie
	global.__objectDepths[282] = -1; // obj_ptooie_pipe
	global.__objectDepths[283] = -1; // obj_spiketop
	global.__objectDepths[284] = -1; // obj_spiketop_blue
	global.__objectDepths[285] = -1; // obj_swoop
	global.__objectDepths[286] = 10; // obj_blargg
	global.__objectDepths[287] = -1; // obj_busterbeetle
	global.__objectDepths[288] = -1; // obj_nokobombette
	global.__objectDepths[289] = -1; // obj_nokobombette_ceiling
	global.__objectDepths[290] = -1; // obj_cheepcheep
	global.__objectDepths[291] = -1; // obj_cheepcheep_v
	global.__objectDepths[292] = -1; // obj_blurp
	global.__objectDepths[293] = -1; // obj_ripvanfish
	global.__objectDepths[294] = -1; // obj_porchupuffer
	global.__objectDepths[295] = -1; // obj_urchin
	global.__objectDepths[296] = -1; // obj_urchin_wall
	global.__objectDepths[297] = 9; // obj_torpedobox
	global.__objectDepths[298] = -1; // obj_blooper
	global.__objectDepths[299] = -1; // obj_huckitcrab
	global.__objectDepths[300] = -2; // obj_dolphin
	global.__objectDepths[301] = -2; // obj_dolphin_jump
	global.__objectDepths[302] = -1; // obj_letterfish
	global.__objectDepths[303] = -1; // obj_letterfish_v
	global.__objectDepths[304] = -2; // obj_lakitu
	global.__objectDepths[305] = -2; // obj_lakitugreen
	global.__objectDepths[306] = -2; // obj_fishinglakitu
	global.__objectDepths[307] = -2; // obj_pipelakitu
	global.__objectDepths[308] = -1; // obj_monty
	global.__objectDepths[309] = -1; // obj_monty_chase
	global.__objectDepths[310] = 8; // obj_monty_dig
	global.__objectDepths[311] = -1; // obj_megamole
	global.__objectDepths[312] = -1; // obj_anttrooper
	global.__objectDepths[313] = -1; // obj_volcanolotus
	global.__objectDepths[314] = -1; // obj_craterlotus
	global.__objectDepths[315] = -1; // obj_fuzzy
	global.__objectDepths[316] = -1; // obj_fuzzy_wall
	global.__objectDepths[317] = -1; // obj_wiggler
	global.__objectDepths[318] = -1; // obj_wiggler_long
	global.__objectDepths[319] = -1; // obj_firesnake
	global.__objectDepths[320] = -1; // obj_pokey
	global.__objectDepths[321] = -2; // obj_angrysun
	global.__objectDepths[322] = -2; // obj_drybones
	global.__objectDepths[323] = -2; // obj_drybones_throw
	global.__objectDepths[324] = -2; // obj_bonybeetle
	global.__objectDepths[325] = -1; // obj_mechakoopa
	global.__objectDepths[326] = -1; // obj_blastakoopa
	global.__objectDepths[327] = -1; // obj_zappakoopa
	global.__objectDepths[328] = 9; // obj_skewer
	global.__objectDepths[329] = 9; // obj_skewer_down
	global.__objectDepths[330] = 9; // obj_skewer_left
	global.__objectDepths[331] = 9; // obj_skewer_right
	global.__objectDepths[332] = 10; // obj_grinder
	global.__objectDepths[333] = -1; // obj_grinder_line
	global.__objectDepths[334] = 9; // obj_firebar
	global.__objectDepths[335] = 0; // obj_rotodisc
	global.__objectDepths[336] = 0; // obj_rotodisc_flower
	global.__objectDepths[337] = 0; // obj_ballnchain
	global.__objectDepths[338] = 10; // obj_podoboo
	global.__objectDepths[339] = -2; // obj_podoboo_diagonal
	global.__objectDepths[340] = -2; // obj_thwimp
	global.__objectDepths[341] = -1; // obj_thwimp_alt
	global.__objectDepths[342] = -1; // obj_thwomp
	global.__objectDepths[343] = -1; // obj_thwomp_left
	global.__objectDepths[344] = -1; // obj_thwomp_right
	global.__objectDepths[345] = -1; // obj_thwomp_mega
	global.__objectDepths[346] = -1; // obj_thwomp_roll
	global.__objectDepths[347] = -2; // obj_magikoopa
	global.__objectDepths[348] = -1; // obj_netkoopa
	global.__objectDepths[349] = -1; // obj_netkoopa_red
	global.__objectDepths[350] = -1; // obj_netkoopa_blue
	global.__objectDepths[351] = -1; // obj_netkoopa_yellow
	global.__objectDepths[352] = -1; // obj_lilspark
	global.__objectDepths[353] = -1; // obj_hothead
	global.__objectDepths[354] = -1; // obj_fallingspike
	global.__objectDepths[355] = -2; // obj_bowserstatue
	global.__objectDepths[356] = -2; // obj_bowserstatue_gold
	global.__objectDepths[357] = -1; // obj_ninji
	global.__objectDepths[358] = -2; // obj_boo
	global.__objectDepths[359] = -2; // obj_booblock
	global.__objectDepths[360] = 0; // obj_boostream
	global.__objectDepths[361] = -2; // obj_boostretch
	global.__objectDepths[362] = -2; // obj_boostretch_ceiling
	global.__objectDepths[363] = -2; // obj_booring
	global.__objectDepths[364] = -2; // obj_bigboo
	global.__objectDepths[365] = -2; // obj_fishinboo
	global.__objectDepths[366] = -2; // obj_eerie
	global.__objectDepths[367] = -2; // obj_eerie_wave
	global.__objectDepths[368] = -1; // obj_slimebubble
	global.__objectDepths[369] = 8; // obj_ghostfloor
	global.__objectDepths[370] = 9; // obj_blaster
	global.__objectDepths[371] = 9; // obj_blaster_missile
	global.__objectDepths[372] = -2; // obj_blaster_pipe
	global.__objectDepths[373] = -2; // obj_blaster_pipe_missile
	global.__objectDepths[374] = 9; // obj_blaster_banzai
	global.__objectDepths[375] = 9; // obj_blaster_bullseye
	global.__objectDepths[376] = -1; // obj_bobomb
	global.__objectDepths[377] = -1; // obj_bobomb_cannon
	global.__objectDepths[378] = -1; // obj_bobomb_parachute
	global.__objectDepths[379] = 9; // obj_cannon
	global.__objectDepths[380] = 9; // obj_cannon_red
	global.__objectDepths[381] = 9; // obj_cannon_bomb
	global.__objectDepths[382] = 9; // obj_cannon_quad
	global.__objectDepths[383] = 9; // obj_cannon_side
	global.__objectDepths[384] = -2; // obj_rengine
	global.__objectDepths[385] = -2; // obj_rengine_alt
	global.__objectDepths[386] = -1; // obj_rockywrench
	global.__objectDepths[387] = 0; // obj_rockywrench_infinite
	global.__objectDepths[388] = -5; // obj_generator_galoomba
	global.__objectDepths[389] = -5; // obj_generator_cheep
	global.__objectDepths[390] = -5; // obj_generator_spinycheep
	global.__objectDepths[391] = -5; // obj_generator_spinycheep_alt
	global.__objectDepths[392] = -5; // obj_generator_dolphin
	global.__objectDepths[393] = 20; // obj_generator_bobomb
	global.__objectDepths[394] = -2; // obj_goomba_the_terrible
	global.__objectDepths[395] = -1; // obj_walrus
	global.__objectDepths[396] = -1; // obj_grayrus
	global.__objectDepths[397] = 10; // obj_chainchomp
	global.__objectDepths[398] = 0; // obj_enemybubble
	global.__objectDepths[399] = 1000000; // obj_mapmanager
	global.__objectDepths[400] = -2; // obj_mapplayer
	global.__objectDepths[401] = 9; // obj_node
	global.__objectDepths[402] = 9; // obj_path_h
	global.__objectDepths[403] = 9; // obj_path_v
	global.__objectDepths[404] = 9; // obj_path_dia_r
	global.__objectDepths[405] = 9; // obj_path_dia_l
	global.__objectDepths[406] = 9; // obj_path_dia2_r
	global.__objectDepths[407] = 9; // obj_path_dia2_l
	global.__objectDepths[408] = 9; // obj_path_dia3_r
	global.__objectDepths[409] = 9; // obj_path_dia3_l
	global.__objectDepths[410] = 9; // obj_path_dia4_r
	global.__objectDepths[411] = 9; // obj_path_dia4_l
	global.__objectDepths[412] = 9; // obj_path_point_l
	global.__objectDepths[413] = 9; // obj_path_point_r
	global.__objectDepths[414] = 9; // obj_path_point_u
	global.__objectDepths[415] = 9; // obj_path_point_d
	global.__objectDepths[416] = 9; // obj_path_corner_ul
	global.__objectDepths[417] = 9; // obj_path_corner_ur
	global.__objectDepths[418] = 9; // obj_path_corner_dr
	global.__objectDepths[419] = 9; // obj_path_corner_dl
	global.__objectDepths[420] = 9; // obj_path_bridge_h
	global.__objectDepths[421] = 9; // obj_path_bridge_v
	global.__objectDepths[422] = 0; // obj_path_ladder
	global.__objectDepths[423] = 8; // obj_levelpipe
	global.__objectDepths[424] = 8; // obj_levelpalace_y
	global.__objectDepths[425] = 8; // obj_levelpalace_g
	global.__objectDepths[426] = 8; // obj_levelpalace_r
	global.__objectDepths[427] = 8; // obj_levelpalace_b
	global.__objectDepths[428] = 8; // obj_levelpanel
	global.__objectDepths[429] = 8; // obj_levelpanel_castle
	global.__objectDepths[430] = 8; // obj_levelpanel_airship
	global.__objectDepths[431] = -1; // obj_mapboo
	global.__objectDepths[432] = -6; // obj_maplakitu
	global.__objectDepths[433] = -1; // obj_mappiranha
	global.__objectDepths[434] = 0; // obj_modifier
	global.__objectDepths[435] = 0; // obj_modifier_novisible
	global.__objectDepths[436] = -10; // obj_lavamask
	global.__objectDepths[437] = -10; // obj_lavamask_slope_r
	global.__objectDepths[438] = -10; // obj_lavamask_slope_l
	global.__objectDepths[439] = -10; // obj_lavamask_slope_sr
	global.__objectDepths[440] = -10; // obj_lavamask_slope_sl
	global.__objectDepths[441] = -6; // obj_lava
	global.__objectDepths[442] = 0; // obj_lava_tides
	global.__objectDepths[443] = 0; // obj_choco_tides
	global.__objectDepths[444] = 0; // obj_poison_tides
	global.__objectDepths[445] = 15; // obj_water
	global.__objectDepths[446] = 15; // obj_water_cave
	global.__objectDepths[447] = 0; // obj_water_tides
	global.__objectDepths[448] = 16; // obj_waterfall
	global.__objectDepths[449] = 8; // obj_muncher
	global.__objectDepths[450] = 12; // obj_seaweed
	global.__objectDepths[451] = 15; // obj_propeller
	global.__objectDepths[452] = -1; // obj_modifier_brick
	global.__objectDepths[453] = -1; // obj_modifier_brick_flip
	global.__objectDepths[454] = -1; // obj_modifier_egg
	global.__objectDepths[455] = -1; // obj_modifier_egg_r
	global.__objectDepths[456] = -1; // obj_modifier_egg_y
	global.__objectDepths[457] = -1; // obj_modifier_egg_b
	global.__objectDepths[458] = -1; // obj_modifier_egg_rainbow
	global.__objectDepths[459] = -1; // obj_modifier_shroom
	global.__objectDepths[460] = -1; // obj_modifier_fireflower
	global.__objectDepths[461] = -1; // obj_modifier_fireflower_alt
	global.__objectDepths[462] = -1; // obj_modifier_feather
	global.__objectDepths[463] = -1; // obj_modifier_feather_alt
	global.__objectDepths[464] = -1; // obj_modifier_iceflower
	global.__objectDepths[465] = -1; // obj_modifier_iceflower_alt
	global.__objectDepths[466] = -1; // obj_modifier_star
	global.__objectDepths[467] = -1; // obj_modifier_1up
	global.__objectDepths[468] = -1; // obj_modifier_poison
	global.__objectDepths[469] = -1; // obj_modifier_watermelon_fire
	global.__objectDepths[470] = -1; // obj_modifier_watermelon_ice
	global.__objectDepths[471] = -1; // obj_modifier_watermelon_bomb
	global.__objectDepths[472] = -1; // obj_modifier_coin_star
	global.__objectDepths[473] = -1; // obj_modifier_coin_multi
	global.__objectDepths[474] = -1; // obj_modifier_coin_multi_shroom
	global.__objectDepths[475] = -1; // obj_modifier_coin_snake
	global.__objectDepths[476] = -1; // obj_modifier_belt_right
	global.__objectDepths[477] = -1; // obj_modifier_belt_right_fast
	global.__objectDepths[478] = -1; // obj_modifier_belt_left
	global.__objectDepths[479] = -1; // obj_modifier_belt_left_fast
	global.__objectDepths[480] = -1; // obj_modifier_pswitch
	global.__objectDepths[481] = -1; // obj_modifier_gswitch
	global.__objectDepths[482] = -1; // obj_modifier_trampoline
	global.__objectDepths[483] = -1; // obj_modifier_powblock
	global.__objectDepths[484] = -1; // obj_modifier_detonator
	global.__objectDepths[485] = -1; // obj_modifier_beanstalk
	global.__objectDepths[486] = -1; // obj_modifier_key
	global.__objectDepths[487] = 0; // obj_soundparent
	global.__objectDepths[488] = -6; // obj_sound_oink_b
	global.__objectDepths[489] = -1; // obj_sound_oink
	global.__objectDepths[490] = 9; // obj_door
	global.__objectDepths[491] = 9; // obj_door_s
	global.__objectDepths[492] = 9; // obj_door_p
	global.__objectDepths[493] = 9; // obj_door_boss
	global.__objectDepths[494] = -2; // obj_warptop_branch
	global.__objectDepths[495] = -2; // obj_warpbottom_branch
	global.__objectDepths[496] = -2; // obj_warpleft_branch
	global.__objectDepths[497] = -2; // obj_warpright_branch
	global.__objectDepths[498] = -2; // obj_warptop
	global.__objectDepths[499] = -2; // obj_warpbottom
	global.__objectDepths[500] = -2; // obj_warpleft
	global.__objectDepths[501] = -2; // obj_warpright
	global.__objectDepths[502] = -4; // obj_warpnode
	global.__objectDepths[503] = 0; // obj_warpparent
	global.__objectDepths[504] = 0; // obj_followme
	global.__objectDepths[505] = -5; // obj_playerparent
	global.__objectDepths[506] = -1; // obj_holdparent
	global.__objectDepths[507] = -1; // obj_holdparent_enemy
	global.__objectDepths[508] = -1; // obj_enemyparent
	global.__objectDepths[509] = -1; // obj_deactenemyparent
	global.__objectDepths[510] = -1; // obj_bossparent
	global.__objectDepths[511] = 0; // obj_solidenemyparent
	global.__objectDepths[512] = 0; // obj_killparent
	global.__objectDepths[513] = -1; // obj_physicsparent
	global.__objectDepths[514] = -1; // obj_powerupparent
	global.__objectDepths[515] = 0; // obj_projectileparent
	global.__objectDepths[516] = 0; // obj_slopeparent
	global.__objectDepths[517] = 0; // obj_slopeparent_move
	global.__objectDepths[518] = -1; // obj_slopeparent_ceiling
	global.__objectDepths[519] = 0; // obj_solid_moving
	global.__objectDepths[520] = 0; // obj_semisolid_moving
	global.__objectDepths[521] = 8; // obj_conveyorparent
	global.__objectDepths[522] = 0; // obj_escalatorparent
	global.__objectDepths[523] = 8; // obj_blockparent
	global.__objectDepths[524] = -1; // obj_modparent
	global.__objectDepths[525] = 0; // obj_trackparent
	global.__objectDepths[526] = 0; // obj_pathparent
	global.__objectDepths[527] = 0; // obj_collisionparent
	global.__objectDepths[528] = 0; // obj_effectsparent
	global.__objectDepths[529] = -1; // obj_iceparent
	global.__objectDepths[530] = 0; // obj_deactivateparent
	global.__objectDepths[531] = 0; // obj_removeme
	global.__objectDepths[532] = -5; // obj_mario
	global.__objectDepths[533] = -5; // obj_luigi
	global.__objectDepths[534] = -5; // obj_toad
	global.__objectDepths[535] = -5; // obj_peach
	global.__objectDepths[536] = -4; // obj_cape
	global.__objectDepths[537] = -5; // obj_cape_fly
	global.__objectDepths[538] = -5; // obj_player_transform
	global.__objectDepths[539] = -5; // obj_player_dead
	global.__objectDepths[540] = -6; // obj_player_clear
	global.__objectDepths[541] = -5; // obj_player_door
	global.__objectDepths[542] = -5; // obj_player_fortress
	global.__objectDepths[543] = -5; // obj_player_wallrunning
	global.__objectDepths[544] = -5; // obj_spinner
	global.__objectDepths[545] = -6; // obj_boundary_top
	global.__objectDepths[546] = -6; // obj_boundary_bottom
	global.__objectDepths[547] = 8; // obj_qblock_scatter
	global.__objectDepths[548] = 8; // obj_brick_flip_b
	global.__objectDepths[549] = -2; // obj_brick_throw_th
	global.__objectDepths[550] = 10; // obj_beanstalk
	global.__objectDepths[551] = -2; // obj_blockcoin
	global.__objectDepths[552] = 10; // obj_coinsnake
	global.__objectDepths[553] = 8; // obj_guessblock
	global.__objectDepths[554] = 10; // obj_egg
	global.__objectDepths[555] = -2; // obj_egg_hatch
	global.__objectDepths[556] = -5; // obj_yoshi
	global.__objectDepths[557] = -2; // obj_yoshi_ice
	global.__objectDepths[558] = -2; // obj_yoshi_fire
	global.__objectDepths[559] = -2; // obj_yoshi_bomb
	global.__objectDepths[560] = 0; // obj_stomp
	global.__objectDepths[561] = -3; // obj_tongue
	global.__objectDepths[562] = 10; // obj_feather_sprout
	global.__objectDepths[563] = -2; // obj_fireball
	global.__objectDepths[564] = -2; // obj_iceball
	global.__objectDepths[565] = -5; // obj_invincibility
	global.__objectDepths[566] = 10; // obj_powerup_sprout
	global.__objectDepths[567] = 9; // obj_powerup_swap
	global.__objectDepths[568] = -9; // obj_reserveitem
	global.__objectDepths[569] = -4; // obj_goal_fade
	global.__objectDepths[570] = -11; // obj_goal_curtain
	global.__objectDepths[571] = -6; // obj_checkpoint_front
	global.__objectDepths[572] = -1; // obj_goal_tape
	global.__objectDepths[573] = -6; // obj_goal_gate_front
	global.__objectDepths[574] = -1; // obj_platform_pulley_right
	global.__objectDepths[575] = 12; // obj_platform_pulley_rope
	global.__objectDepths[576] = 13; // obj_platform_ferris_chain
	global.__objectDepths[577] = -1; // obj_platform_ferris_platform
	global.__objectDepths[578] = 0; // obj_accordion_block
	global.__objectDepths[579] = -1; // obj_donut_ticker
	global.__objectDepths[580] = 0; // obj_engine_rope
	global.__objectDepths[581] = 0; // obj_engine_blade
	global.__objectDepths[582] = -1; // obj_boltlift_fall
	global.__objectDepths[583] = -2; // obj_boltlift_top
	global.__objectDepths[584] = -1; // obj_blocktrain_front
	global.__objectDepths[585] = -1; // obj_blocktrain_back
	global.__objectDepths[586] = 0; // obj_blocktrain_middle
	global.__objectDepths[587] = 0; // obj_blocktrain_killer
	global.__objectDepths[588] = -2; // obj_powblock_active
	global.__objectDepths[589] = 0; // obj_powblock_killer
	global.__objectDepths[590] = 0; // obj_icicle_shard
	global.__objectDepths[591] = -6; // obj_lakitucloud_front
	global.__objectDepths[592] = 0; // obj_coin_alt
	global.__objectDepths[593] = 0; // obj_coin_silver
	global.__objectDepths[594] = 0; // obj_coinchange
	global.__objectDepths[595] = 0; // obj_explosion
	global.__objectDepths[596] = -6; // obj_explosion_stars
	global.__objectDepths[597] = -6; // obj_twister_bubble
	global.__objectDepths[598] = -5; // obj_enemy_dead
	global.__objectDepths[599] = 0; // obj_enemy_multidead
	global.__objectDepths[600] = -5; // obj_enemy_stomped
	global.__objectDepths[601] = -7; // obj_enemy_score
	global.__objectDepths[602] = -2; // obj_enemy_frozen
	global.__objectDepths[603] = 0; // obj_enemy_tick
	global.__objectDepths[604] = 0; // obj_microgoomba
	global.__objectDepths[605] = -2; // obj_galoomba_held
	global.__objectDepths[606] = -4; // obj_hammerbro_hammer
	global.__objectDepths[607] = -4; // obj_boomerangbro_boomerang
	global.__objectDepths[608] = -2; // obj_firebro_fireball
	global.__objectDepths[609] = -1; // obj_afhb_rider
	global.__objectDepths[610] = -2; // obj_sumobro_flame
	global.__objectDepths[611] = -2; // obj_sumobro_lightning
	global.__objectDepths[612] = -1; // obj_football
	global.__objectDepths[613] = -1; // obj_mudball
	global.__objectDepths[614] = -1; // obj_baseball
	global.__objectDepths[615] = -2; // obj_dinotorch_flame
	global.__objectDepths[616] = -2; // obj_spike_ball
	global.__objectDepths[617] = -1; // obj_spiny_thrown
	global.__objectDepths[618] = -1; // obj_spiny_green
	global.__objectDepths[619] = 11; // obj_plantfire
	global.__objectDepths[620] = 13; // obj_plantfire2
	global.__objectDepths[621] = -2; // obj_ptooie_ball
	global.__objectDepths[622] = -1; // obj_ptooie_bubble
	global.__objectDepths[623] = 10; // obj_blargg_jump
	global.__objectDepths[624] = -1; // obj_busterpickup
	global.__objectDepths[625] = -2; // obj_torpedoted
	global.__objectDepths[626] = -2; // obj_huckitcrab_rock
	global.__objectDepths[627] = 0; // obj_lakitubait
	global.__objectDepths[628] = -1; // obj_monty_jump
	global.__objectDepths[629] = -2; // obj_lotusball
	global.__objectDepths[630] = -2; // obj_lotusball_homing
	global.__objectDepths[631] = 0; // obj_wiggler_body
	global.__objectDepths[632] = 0; // obj_firesnake_trail
	global.__objectDepths[633] = -5; // obj_pokey_dead
	global.__objectDepths[634] = 0; // obj_angrysun_movement
	global.__objectDepths[635] = -2; // obj_crumblebones
	global.__objectDepths[636] = -4; // obj_drybones_bone
	global.__objectDepths[637] = -2; // obj_blastakoopa_bullet
	global.__objectDepths[638] = -2; // obj_zappakoopa_beam
	global.__objectDepths[639] = -3; // obj_zappakoopa_beameff
	global.__objectDepths[640] = -2; // obj_zappakoopa_laser
	global.__objectDepths[641] = -2; // obj_mechakoopa_held
	global.__objectDepths[642] = -5; // obj_mechakoopa_debris
	global.__objectDepths[643] = 0; // obj_skewerparent
	global.__objectDepths[644] = -1; // obj_skewertrunk
	global.__objectDepths[645] = -1; // obj_skewertrunk_down
	global.__objectDepths[646] = -1; // obj_skewertrunk_left
	global.__objectDepths[647] = -1; // obj_skewertrunk_right
	global.__objectDepths[648] = -2; // obj_firebar_ball
	global.__objectDepths[649] = -2; // obj_rotodisc_disc
	global.__objectDepths[650] = -2; // obj_rotodisc_flower_disc
	global.__objectDepths[651] = -1; // obj_rotodisc_trail
	global.__objectDepths[652] = -2; // obj_ballnchain_ball
	global.__objectDepths[653] = -1; // obj_ballnchain_chain
	global.__objectDepths[654] = -1; // obj_magic
	global.__objectDepths[655] = -1; // obj_bowserstatue_fire
	global.__objectDepths[656] = -1; // obj_boo_trail
	global.__objectDepths[657] = -3; // obj_booring_boo
	global.__objectDepths[658] = 10; // obj_bulletbill
	global.__objectDepths[659] = 10; // obj_missilebill
	global.__objectDepths[660] = 10; // obj_banzaibill
	global.__objectDepths[661] = 10; // obj_bullseyebanzai
	global.__objectDepths[662] = -2; // obj_bobomb_held
	global.__objectDepths[663] = -2; // obj_cannon_ball
	global.__objectDepths[664] = -2; // obj_rockywrench_wrench
	global.__objectDepths[665] = -1; // obj_cheepcheep_gen
	global.__objectDepths[666] = -1; // obj_spinycheep
	global.__objectDepths[667] = -1; // obj_spinycheep_swim
	global.__objectDepths[668] = -2; // obj_dolphin_gen
	global.__objectDepths[669] = -2; // obj_shell_kicked
	global.__objectDepths[670] = -1; // obj_chomp
	global.__objectDepths[671] = 0; // obj_chomp_chain
	global.__objectDepths[672] = 0; // obj_enemybubble_respawn
	global.__objectDepths[673] = -6; // obj_mapcloud
	global.__objectDepths[674] = -2; // obj_mapopener
	global.__objectDepths[675] = 0; // obj_mapplayer_switcher
	global.__objectDepths[676] = 0; // obj_light_lava_top
	global.__objectDepths[677] = 0; // obj_light_lava_bottom
	global.__objectDepths[678] = -6; // obj_ring
	global.__objectDepths[679] = -6; // obj_ring_pow
	global.__objectDepths[680] = 0; // obj_light_rengine
	global.__objectDepths[681] = 0; // obj_light_disco_gen
	global.__objectDepths[682] = -6; // obj_score
	global.__objectDepths[683] = -10; // obj_score_goal
	global.__objectDepths[684] = -6; // obj_shard
	global.__objectDepths[685] = 0; // obj_shard_switch
	global.__objectDepths[686] = 0; // obj_blob
	global.__objectDepths[687] = -6; // obj_bubble
	global.__objectDepths[688] = -6; // obj_bubble_h
	global.__objectDepths[689] = 0; // obj_cloud
	global.__objectDepths[690] = -6; // obj_note
	global.__objectDepths[691] = -6; // obj_rain
	global.__objectDepths[692] = -6; // obj_shellthump
	global.__objectDepths[693] = -6; // obj_smoke
	global.__objectDepths[694] = -6; // obj_smoke_water
	global.__objectDepths[695] = -6; // obj_snow
	global.__objectDepths[696] = -6; // obj_sparkle
	global.__objectDepths[697] = -6; // obj_spinsmoke
	global.__objectDepths[698] = -5; // obj_spinstar
	global.__objectDepths[699] = -6; // obj_spinthump
	global.__objectDepths[700] = 16; // obj_castledoor
	global.__objectDepths[701] = 20; // obj_castledoor_black
	global.__objectDepths[702] = -11; // obj_dialog
	global.__objectDepths[703] = -11; // obj_message
	global.__objectDepths[704] = -15; // obj_save
	global.__objectDepths[705] = -7; // obj_credits
	global.__objectDepths[706] = -6; // obj_title_menu_key
	global.__objectDepths[707] = -6; // obj_title
	global.__objectDepths[708] = -5; // obj_title_player
	global.__objectDepths[709] = 0; // obj_audio_loop_sound
	global.__objectDepths[710] = -7; // obj_fish
	global.__objectDepths[711] = -10; // obj_hud
	global.__objectDepths[712] = -10; // obj_hud_map
	global.__objectDepths[713] = -15; // obj_pause
	global.__objectDepths[714] = 0; // obj_blockbumper
	global.__objectDepths[715] = 100000; // obj_lightningsheet
	global.__objectDepths[716] = 0; // obj_intro
	global.__objectDepths[717] = -1; // obj_npc
	global.__objectDepths[718] = 0; // obj_noyoshi_cutscene
	global.__objectDepths[719] = -99; // obj_controller1
	global.__objectDepths[720] = -100; // obj_mariostart
	global.__objectDepths[721] = 10; // obj_gameover
	global.__objectDepths[722] = 9; // obj_palaceswitch
	global.__objectDepths[723] = 8; // obj_bonusblock_center
	global.__objectDepths[724] = 7; // obj_bonusblock
	global.__objectDepths[725] = -2; // obj_up
	global.__objectDepths[726] = -2; // obj_down
	global.__objectDepths[727] = -2; // obj_left
	global.__objectDepths[728] = -2; // obj_right
	global.__objectDepths[729] = -2; // obj_endmarker


	global.__objectNames[0] = "obj_player";
	global.__objectNames[1] = "obj_player_warp";
	global.__objectNames[2] = "obj_light";
	global.__objectNames[3] = "obj_light_npc";
	global.__objectNames[4] = "obj_light_static";
	global.__objectNames[5] = "obj_light_disco";
	global.__objectNames[6] = "obj_lightparent";
	global.__objectNames[7] = "obj_lightcontrol";
	global.__objectNames[8] = "obj_checkpoint";
	global.__objectNames[9] = "obj_checkpoint_tape";
	global.__objectNames[10] = "obj_goal_gate";
	global.__objectNames[11] = "obj_orb";
	global.__objectNames[12] = "obj_keyhole";
	global.__objectNames[13] = "obj_rainmaker";
	global.__objectNames[14] = "obj_snowmaker";
	global.__objectNames[15] = "obj_tilehider";
	global.__objectNames[16] = "obj_autoscroll";
	global.__objectNames[17] = "obj_bganimator";
	global.__objectNames[18] = "obj_levelcontrol";
	global.__objectNames[19] = "obj_guessblock_manager";
	global.__objectNames[20] = "obj_tilemanager";
	global.__objectNames[21] = "obj_tilemanager_fall";
	global.__objectNames[22] = "obj_tilesolid";
	global.__objectNames[23] = "obj_tilesemisolid";
	global.__objectNames[24] = "obj_tilehurt";
	global.__objectNames[25] = "obj_solid";
	global.__objectNames[26] = "obj_semisolid";
	global.__objectNames[27] = "obj_climb";
	global.__objectNames[28] = "obj_climb_net";
	global.__objectNames[29] = "obj_swim";
	global.__objectNames[30] = "obj_ceiling_slope_r";
	global.__objectNames[31] = "obj_ceiling_slope_l";
	global.__objectNames[32] = "obj_ceiling_slope_steep_r";
	global.__objectNames[33] = "obj_ceiling_slope_steep_l";
	global.__objectNames[34] = "obj_slope_r";
	global.__objectNames[35] = "obj_slope_l";
	global.__objectNames[36] = "obj_slope_wide_r";
	global.__objectNames[37] = "obj_slope_wide_l";
	global.__objectNames[38] = "obj_slope_steep_r";
	global.__objectNames[39] = "obj_slope_steep_l";
	global.__objectNames[40] = "obj_slope_steeper_r";
	global.__objectNames[41] = "obj_slope_steeper_l";
	global.__objectNames[42] = "obj_slope_trunk_r";
	global.__objectNames[43] = "obj_slope_trunk_l";
	global.__objectNames[44] = "obj_slippery";
	global.__objectNames[45] = "obj_slippery_slope_r";
	global.__objectNames[46] = "obj_slippery_slope_l";
	global.__objectNames[47] = "obj_slippery_slope_steep_r";
	global.__objectNames[48] = "obj_slippery_slope_steep_l";
	global.__objectNames[49] = "obj_hurtblock";
	global.__objectNames[50] = "obj_hurtblock_lethal";
	global.__objectNames[51] = "obj_block_mario";
	global.__objectNames[52] = "obj_block_luigi";
	global.__objectNames[53] = "obj_block_toad";
	global.__objectNames[54] = "obj_block_peach";
	global.__objectNames[55] = "obj_area_big_y";
	global.__objectNames[56] = "obj_area_big_g";
	global.__objectNames[57] = "obj_area_big_r";
	global.__objectNames[58] = "obj_area_big_b";
	global.__objectNames[59] = "obj_area_y";
	global.__objectNames[60] = "obj_area_g";
	global.__objectNames[61] = "obj_area_r";
	global.__objectNames[62] = "obj_area_b";
	global.__objectNames[63] = "obj_qblock_big";
	global.__objectNames[64] = "obj_qblock_hidden";
	global.__objectNames[65] = "obj_qblock";
	global.__objectNames[66] = "obj_qblock_winged";
	global.__objectNames[67] = "obj_emptyblock";
	global.__objectNames[68] = "obj_brick_big";
	global.__objectNames[69] = "obj_brick_flip_big";
	global.__objectNames[70] = "obj_brick";
	global.__objectNames[71] = "obj_brick_flip";
	global.__objectNames[72] = "obj_brick_throw";
	global.__objectNames[73] = "obj_brick_fragile";
	global.__objectNames[74] = "obj_brick_crystal";
	global.__objectNames[75] = "obj_brick_stone";
	global.__objectNames[76] = "obj_msgblock";
	global.__objectNames[77] = "obj_noteblock";
	global.__objectNames[78] = "obj_noteblock_hidden";
	global.__objectNames[79] = "obj_noteblock_diagonal_r";
	global.__objectNames[80] = "obj_noteblock_diagonal_l";
	global.__objectNames[81] = "obj_quaverblock";
	global.__objectNames[82] = "obj_playerblock";
	global.__objectNames[83] = "obj_woodblock";
	global.__objectNames[84] = "obj_yblock";
	global.__objectNames[85] = "obj_iceblock";
	global.__objectNames[86] = "obj_iceblock_coin";
	global.__objectNames[87] = "obj_iceblock_muncher";
	global.__objectNames[88] = "obj_viewblock";
	global.__objectNames[89] = "obj_powblock";
	global.__objectNames[90] = "obj_lightblock";
	global.__objectNames[91] = "obj_lightblock_disco";
	global.__objectNames[92] = "obj_onoffblock";
	global.__objectNames[93] = "obj_onoffplatform_red";
	global.__objectNames[94] = "obj_onoffplatform_blue";
	global.__objectNames[95] = "obj_starblock";
	global.__objectNames[96] = "obj_conveyor";
	global.__objectNames[97] = "obj_escalator_r";
	global.__objectNames[98] = "obj_escalator_l";
	global.__objectNames[99] = "obj_escalator_down_r";
	global.__objectNames[100] = "obj_escalator_down_l";
	global.__objectNames[101] = "obj_escalator_joint";
	global.__objectNames[102] = "obj_track_dia_r_on";
	global.__objectNames[103] = "obj_track_dia_r_off";
	global.__objectNames[104] = "obj_track_dia_l_on";
	global.__objectNames[105] = "obj_track_dia_l_off";
	global.__objectNames[106] = "obj_track_modifier";
	global.__objectNames[107] = "obj_track_limit";
	global.__objectNames[108] = "obj_track_h";
	global.__objectNames[109] = "obj_track_v";
	global.__objectNames[110] = "obj_track_dia_r";
	global.__objectNames[111] = "obj_track_dia_l";
	global.__objectNames[112] = "obj_track_circle";
	global.__objectNames[113] = "obj_track_circle_2x";
	global.__objectNames[114] = "obj_platform";
	global.__objectNames[115] = "obj_platform_path";
	global.__objectNames[116] = "obj_platform_falling";
	global.__objectNames[117] = "obj_platform_pulley";
	global.__objectNames[118] = "obj_platform_seesaw";
	global.__objectNames[119] = "obj_platform_island";
	global.__objectNames[120] = "obj_platform_crate";
	global.__objectNames[121] = "obj_platform_ferris";
	global.__objectNames[122] = "obj_platform_yoshi";
	global.__objectNames[123] = "obj_platform_track";
	global.__objectNames[124] = "obj_platform_track_blue";
	global.__objectNames[125] = "obj_platform_accordion_h";
	global.__objectNames[126] = "obj_platform_accordion_v";
	global.__objectNames[127] = "obj_platform_accordion_hv";
	global.__objectNames[128] = "obj_platform_accordian_diag";
	global.__objectNames[129] = "obj_platform_slope_r";
	global.__objectNames[130] = "obj_platform_slope_l";
	global.__objectNames[131] = "obj_platform_timed";
	global.__objectNames[132] = "obj_platform_arrow";
	global.__objectNames[133] = "obj_platform_arrow_l";
	global.__objectNames[134] = "obj_platform_arrow_r";
	global.__objectNames[135] = "obj_movingpipe";
	global.__objectNames[136] = "obj_movingrope";
	global.__objectNames[137] = "obj_movingsaw";
	global.__objectNames[138] = "obj_movingseesaw";
	global.__objectNames[139] = "obj_skullraft";
	global.__objectNames[140] = "obj_donut";
	global.__objectNames[141] = "obj_donut_triple";
	global.__objectNames[142] = "obj_donut_red";
	global.__objectNames[143] = "obj_donut_red_triple";
	global.__objectNames[144] = "obj_donut_ice";
	global.__objectNames[145] = "obj_donut_ice_triple";
	global.__objectNames[146] = "obj_boltlift";
	global.__objectNames[147] = "obj_blocktrain";
	global.__objectNames[148] = "obj_pswitch";
	global.__objectNames[149] = "obj_gswitch";
	global.__objectNames[150] = "obj_trampoline";
	global.__objectNames[151] = "obj_trampoline_timed";
	global.__objectNames[152] = "obj_powblock_blue";
	global.__objectNames[153] = "obj_pblock_on";
	global.__objectNames[154] = "obj_pblock_off";
	global.__objectNames[155] = "obj_walltrampoline";
	global.__objectNames[156] = "obj_walltriangle_r";
	global.__objectNames[157] = "obj_walltriangle_l";
	global.__objectNames[158] = "obj_glowblock";
	global.__objectNames[159] = "obj_crate";
	global.__objectNames[160] = "obj_spikeblock";
	global.__objectNames[161] = "obj_spikeblock_g";
	global.__objectNames[162] = "obj_spikeblock_red";
	global.__objectNames[163] = "obj_spikeblock_blue";
	global.__objectNames[164] = "obj_beepblock_red";
	global.__objectNames[165] = "obj_beepblock_blue";
	global.__objectNames[166] = "obj_boostpanel";
	global.__objectNames[167] = "obj_bombblock";
	global.__objectNames[168] = "obj_deathblock";
	global.__objectNames[169] = "obj_floodblock";
	global.__objectNames[170] = "obj_floodblock_reset";
	global.__objectNames[171] = "obj_icicle";
	global.__objectNames[172] = "obj_icicle_static";
	global.__objectNames[173] = "obj_detonator";
	global.__objectNames[174] = "obj_beanstalk_vine";
	global.__objectNames[175] = "obj_lakitucloud";
	global.__objectNames[176] = "obj_spiketrap";
	global.__objectNames[177] = "obj_bumper";
	global.__objectNames[178] = "obj_key";
	global.__objectNames[179] = "obj_coin";
	global.__objectNames[180] = "obj_coin_p";
	global.__objectNames[181] = "obj_coin_5";
	global.__objectNames[182] = "obj_coin_10";
	global.__objectNames[183] = "obj_coin_ace";
	global.__objectNames[184] = "obj_coin_outline";
	global.__objectNames[185] = "obj_mushroom";
	global.__objectNames[186] = "obj_mushroom_h";
	global.__objectNames[187] = "obj_fireflower";
	global.__objectNames[188] = "obj_feather";
	global.__objectNames[189] = "obj_iceflower";
	global.__objectNames[190] = "obj_star";
	global.__objectNames[191] = "obj_1up";
	global.__objectNames[192] = "obj_1up_h1";
	global.__objectNames[193] = "obj_1up_h2";
	global.__objectNames[194] = "obj_1up_h3";
	global.__objectNames[195] = "obj_1up_h4";
	global.__objectNames[196] = "obj_poison";
	global.__objectNames[197] = "obj_watermelon_fire";
	global.__objectNames[198] = "obj_watermelon_ice";
	global.__objectNames[199] = "obj_watermelon_bomb";
	global.__objectNames[200] = "obj_3upmoon";
	global.__objectNames[201] = "obj_twister";
	global.__objectNames[202] = "obj_goomba_hefty";
	global.__objectNames[203] = "obj_goomba_big";
	global.__objectNames[204] = "obj_goomba";
	global.__objectNames[205] = "obj_paragoomba";
	global.__objectNames[206] = "obj_paragoomba_red";
	global.__objectNames[207] = "obj_galoomba";
	global.__objectNames[208] = "obj_galoomba_parachute";
	global.__objectNames[209] = "obj_paragaloomba";
	global.__objectNames[210] = "obj_galoomba_red";
	global.__objectNames[211] = "obj_goombud";
	global.__objectNames[212] = "obj_supergoomba";
	global.__objectNames[213] = "obj_trolloomba";
	global.__objectNames[214] = "obj_bigkoopa";
	global.__objectNames[215] = "obj_bigparakoopa";
	global.__objectNames[216] = "obj_bigparakoopa_super";
	global.__objectNames[217] = "obj_bigparakoopa_fly";
	global.__objectNames[218] = "obj_bigbeachkoopa";
	global.__objectNames[219] = "obj_classickoopa";
	global.__objectNames[220] = "obj_classicparakoopa";
	global.__objectNames[221] = "obj_classicparakoopa_fly";
	global.__objectNames[222] = "obj_superkoopa_green";
	global.__objectNames[223] = "obj_koopa";
	global.__objectNames[224] = "obj_parakoopa";
	global.__objectNames[225] = "obj_parakoopa_super";
	global.__objectNames[226] = "obj_parakoopa_fly";
	global.__objectNames[227] = "obj_beachkoopa";
	global.__objectNames[228] = "obj_bigkoopa_red";
	global.__objectNames[229] = "obj_bigbeachkoopa_red";
	global.__objectNames[230] = "obj_classickoopa_red";
	global.__objectNames[231] = "obj_classicparakoopa_red";
	global.__objectNames[232] = "obj_classicparakoopa_red_hor";
	global.__objectNames[233] = "obj_superkoopa_red";
	global.__objectNames[234] = "obj_koopa_red";
	global.__objectNames[235] = "obj_parakoopa_red";
	global.__objectNames[236] = "obj_parakoopa_red_hor";
	global.__objectNames[237] = "obj_beachkoopa_red";
	global.__objectNames[238] = "obj_superkoopa";
	global.__objectNames[239] = "obj_koopa_blue";
	global.__objectNames[240] = "obj_parakoopa_blue";
	global.__objectNames[241] = "obj_beachkoopa_blue";
	global.__objectNames[242] = "obj_koopa_yellow";
	global.__objectNames[243] = "obj_parakoopa_yellow";
	global.__objectNames[244] = "obj_parakoopa_yellow_wave";
	global.__objectNames[245] = "obj_beachkoopa_yellow";
	global.__objectNames[246] = "obj_shell";
	global.__objectNames[247] = "obj_shell_kamikaze";
	global.__objectNames[248] = "obj_hammerbro";
	global.__objectNames[249] = "obj_boomerangbro";
	global.__objectNames[250] = "obj_firebro";
	global.__objectNames[251] = "obj_sledgebro";
	global.__objectNames[252] = "obj_afhb";
	global.__objectNames[253] = "obj_sumobro";
	global.__objectNames[254] = "obj_rex";
	global.__objectNames[255] = "obj_rex_red";
	global.__objectNames[256] = "obj_charginchuck";
	global.__objectNames[257] = "obj_clappinchuck";
	global.__objectNames[258] = "obj_confusedchuck";
	global.__objectNames[259] = "obj_bouncinchuck";
	global.__objectNames[260] = "obj_digginchuck";
	global.__objectNames[261] = "obj_passinchuck";
	global.__objectNames[262] = "obj_splittinchuck";
	global.__objectNames[263] = "obj_whistlinchuck";
	global.__objectNames[264] = "obj_dinotorch";
	global.__objectNames[265] = "obj_dinorhino";
	global.__objectNames[266] = "obj_spike";
	global.__objectNames[267] = "obj_buzzybeetle";
	global.__objectNames[268] = "obj_buzzybeetle_ceiling";
	global.__objectNames[269] = "obj_spiny";
	global.__objectNames[270] = "obj_spiny_alt";
	global.__objectNames[271] = "obj_spiny_ceiling";
	global.__objectNames[272] = "obj_piranhacus";
	global.__objectNames[273] = "obj_longpiranhacus";
	global.__objectNames[274] = "obj_piranhaplant";
	global.__objectNames[275] = "obj_piranhaplant_long";
	global.__objectNames[276] = "obj_piranhaplant_long_down";
	global.__objectNames[277] = "obj_fireplant";
	global.__objectNames[278] = "obj_fireplant_long";
	global.__objectNames[279] = "obj_fireplant_long_down";
	global.__objectNames[280] = "obj_jumpplant";
	global.__objectNames[281] = "obj_ptooie";
	global.__objectNames[282] = "obj_ptooie_pipe";
	global.__objectNames[283] = "obj_spiketop";
	global.__objectNames[284] = "obj_spiketop_blue";
	global.__objectNames[285] = "obj_swoop";
	global.__objectNames[286] = "obj_blargg";
	global.__objectNames[287] = "obj_busterbeetle";
	global.__objectNames[288] = "obj_nokobombette";
	global.__objectNames[289] = "obj_nokobombette_ceiling";
	global.__objectNames[290] = "obj_cheepcheep";
	global.__objectNames[291] = "obj_cheepcheep_v";
	global.__objectNames[292] = "obj_blurp";
	global.__objectNames[293] = "obj_ripvanfish";
	global.__objectNames[294] = "obj_porchupuffer";
	global.__objectNames[295] = "obj_urchin";
	global.__objectNames[296] = "obj_urchin_wall";
	global.__objectNames[297] = "obj_torpedobox";
	global.__objectNames[298] = "obj_blooper";
	global.__objectNames[299] = "obj_huckitcrab";
	global.__objectNames[300] = "obj_dolphin";
	global.__objectNames[301] = "obj_dolphin_jump";
	global.__objectNames[302] = "obj_letterfish";
	global.__objectNames[303] = "obj_letterfish_v";
	global.__objectNames[304] = "obj_lakitu";
	global.__objectNames[305] = "obj_lakitugreen";
	global.__objectNames[306] = "obj_fishinglakitu";
	global.__objectNames[307] = "obj_pipelakitu";
	global.__objectNames[308] = "obj_monty";
	global.__objectNames[309] = "obj_monty_chase";
	global.__objectNames[310] = "obj_monty_dig";
	global.__objectNames[311] = "obj_megamole";
	global.__objectNames[312] = "obj_anttrooper";
	global.__objectNames[313] = "obj_volcanolotus";
	global.__objectNames[314] = "obj_craterlotus";
	global.__objectNames[315] = "obj_fuzzy";
	global.__objectNames[316] = "obj_fuzzy_wall";
	global.__objectNames[317] = "obj_wiggler";
	global.__objectNames[318] = "obj_wiggler_long";
	global.__objectNames[319] = "obj_firesnake";
	global.__objectNames[320] = "obj_pokey";
	global.__objectNames[321] = "obj_angrysun";
	global.__objectNames[322] = "obj_drybones";
	global.__objectNames[323] = "obj_drybones_throw";
	global.__objectNames[324] = "obj_bonybeetle";
	global.__objectNames[325] = "obj_mechakoopa";
	global.__objectNames[326] = "obj_blastakoopa";
	global.__objectNames[327] = "obj_zappakoopa";
	global.__objectNames[328] = "obj_skewer";
	global.__objectNames[329] = "obj_skewer_down";
	global.__objectNames[330] = "obj_skewer_left";
	global.__objectNames[331] = "obj_skewer_right";
	global.__objectNames[332] = "obj_grinder";
	global.__objectNames[333] = "obj_grinder_line";
	global.__objectNames[334] = "obj_firebar";
	global.__objectNames[335] = "obj_rotodisc";
	global.__objectNames[336] = "obj_rotodisc_flower";
	global.__objectNames[337] = "obj_ballnchain";
	global.__objectNames[338] = "obj_podoboo";
	global.__objectNames[339] = "obj_podoboo_diagonal";
	global.__objectNames[340] = "obj_thwimp";
	global.__objectNames[341] = "obj_thwimp_alt";
	global.__objectNames[342] = "obj_thwomp";
	global.__objectNames[343] = "obj_thwomp_left";
	global.__objectNames[344] = "obj_thwomp_right";
	global.__objectNames[345] = "obj_thwomp_mega";
	global.__objectNames[346] = "obj_thwomp_roll";
	global.__objectNames[347] = "obj_magikoopa";
	global.__objectNames[348] = "obj_netkoopa";
	global.__objectNames[349] = "obj_netkoopa_red";
	global.__objectNames[350] = "obj_netkoopa_blue";
	global.__objectNames[351] = "obj_netkoopa_yellow";
	global.__objectNames[352] = "obj_lilspark";
	global.__objectNames[353] = "obj_hothead";
	global.__objectNames[354] = "obj_fallingspike";
	global.__objectNames[355] = "obj_bowserstatue";
	global.__objectNames[356] = "obj_bowserstatue_gold";
	global.__objectNames[357] = "obj_ninji";
	global.__objectNames[358] = "obj_boo";
	global.__objectNames[359] = "obj_booblock";
	global.__objectNames[360] = "obj_boostream";
	global.__objectNames[361] = "obj_boostretch";
	global.__objectNames[362] = "obj_boostretch_ceiling";
	global.__objectNames[363] = "obj_booring";
	global.__objectNames[364] = "obj_bigboo";
	global.__objectNames[365] = "obj_fishinboo";
	global.__objectNames[366] = "obj_eerie";
	global.__objectNames[367] = "obj_eerie_wave";
	global.__objectNames[368] = "obj_slimebubble";
	global.__objectNames[369] = "obj_ghostfloor";
	global.__objectNames[370] = "obj_blaster";
	global.__objectNames[371] = "obj_blaster_missile";
	global.__objectNames[372] = "obj_blaster_pipe";
	global.__objectNames[373] = "obj_blaster_pipe_missile";
	global.__objectNames[374] = "obj_blaster_banzai";
	global.__objectNames[375] = "obj_blaster_bullseye";
	global.__objectNames[376] = "obj_bobomb";
	global.__objectNames[377] = "obj_bobomb_cannon";
	global.__objectNames[378] = "obj_bobomb_parachute";
	global.__objectNames[379] = "obj_cannon";
	global.__objectNames[380] = "obj_cannon_red";
	global.__objectNames[381] = "obj_cannon_bomb";
	global.__objectNames[382] = "obj_cannon_quad";
	global.__objectNames[383] = "obj_cannon_side";
	global.__objectNames[384] = "obj_rengine";
	global.__objectNames[385] = "obj_rengine_alt";
	global.__objectNames[386] = "obj_rockywrench";
	global.__objectNames[387] = "obj_rockywrench_infinite";
	global.__objectNames[388] = "obj_generator_galoomba";
	global.__objectNames[389] = "obj_generator_cheep";
	global.__objectNames[390] = "obj_generator_spinycheep";
	global.__objectNames[391] = "obj_generator_spinycheep_alt";
	global.__objectNames[392] = "obj_generator_dolphin";
	global.__objectNames[393] = "obj_generator_bobomb";
	global.__objectNames[394] = "obj_goomba_the_terrible";
	global.__objectNames[395] = "obj_walrus";
	global.__objectNames[396] = "obj_grayrus";
	global.__objectNames[397] = "obj_chainchomp";
	global.__objectNames[398] = "obj_enemybubble";
	global.__objectNames[399] = "obj_mapmanager";
	global.__objectNames[400] = "obj_mapplayer";
	global.__objectNames[401] = "obj_node";
	global.__objectNames[402] = "obj_path_h";
	global.__objectNames[403] = "obj_path_v";
	global.__objectNames[404] = "obj_path_dia_r";
	global.__objectNames[405] = "obj_path_dia_l";
	global.__objectNames[406] = "obj_path_dia2_r";
	global.__objectNames[407] = "obj_path_dia2_l";
	global.__objectNames[408] = "obj_path_dia3_r";
	global.__objectNames[409] = "obj_path_dia3_l";
	global.__objectNames[410] = "obj_path_dia4_r";
	global.__objectNames[411] = "obj_path_dia4_l";
	global.__objectNames[412] = "obj_path_point_l";
	global.__objectNames[413] = "obj_path_point_r";
	global.__objectNames[414] = "obj_path_point_u";
	global.__objectNames[415] = "obj_path_point_d";
	global.__objectNames[416] = "obj_path_corner_ul";
	global.__objectNames[417] = "obj_path_corner_ur";
	global.__objectNames[418] = "obj_path_corner_dr";
	global.__objectNames[419] = "obj_path_corner_dl";
	global.__objectNames[420] = "obj_path_bridge_h";
	global.__objectNames[421] = "obj_path_bridge_v";
	global.__objectNames[422] = "obj_path_ladder";
	global.__objectNames[423] = "obj_levelpipe";
	global.__objectNames[424] = "obj_levelpalace_y";
	global.__objectNames[425] = "obj_levelpalace_g";
	global.__objectNames[426] = "obj_levelpalace_r";
	global.__objectNames[427] = "obj_levelpalace_b";
	global.__objectNames[428] = "obj_levelpanel";
	global.__objectNames[429] = "obj_levelpanel_castle";
	global.__objectNames[430] = "obj_levelpanel_airship";
	global.__objectNames[431] = "obj_mapboo";
	global.__objectNames[432] = "obj_maplakitu";
	global.__objectNames[433] = "obj_mappiranha";
	global.__objectNames[434] = "obj_modifier";
	global.__objectNames[435] = "obj_modifier_novisible";
	global.__objectNames[436] = "obj_lavamask";
	global.__objectNames[437] = "obj_lavamask_slope_r";
	global.__objectNames[438] = "obj_lavamask_slope_l";
	global.__objectNames[439] = "obj_lavamask_slope_sr";
	global.__objectNames[440] = "obj_lavamask_slope_sl";
	global.__objectNames[441] = "obj_lava";
	global.__objectNames[442] = "obj_lava_tides";
	global.__objectNames[443] = "obj_choco_tides";
	global.__objectNames[444] = "obj_poison_tides";
	global.__objectNames[445] = "obj_water";
	global.__objectNames[446] = "obj_water_cave";
	global.__objectNames[447] = "obj_water_tides";
	global.__objectNames[448] = "obj_waterfall";
	global.__objectNames[449] = "obj_muncher";
	global.__objectNames[450] = "obj_seaweed";
	global.__objectNames[451] = "obj_propeller";
	global.__objectNames[452] = "obj_modifier_brick";
	global.__objectNames[453] = "obj_modifier_brick_flip";
	global.__objectNames[454] = "obj_modifier_egg";
	global.__objectNames[455] = "obj_modifier_egg_r";
	global.__objectNames[456] = "obj_modifier_egg_y";
	global.__objectNames[457] = "obj_modifier_egg_b";
	global.__objectNames[458] = "obj_modifier_egg_rainbow";
	global.__objectNames[459] = "obj_modifier_shroom";
	global.__objectNames[460] = "obj_modifier_fireflower";
	global.__objectNames[461] = "obj_modifier_fireflower_alt";
	global.__objectNames[462] = "obj_modifier_feather";
	global.__objectNames[463] = "obj_modifier_feather_alt";
	global.__objectNames[464] = "obj_modifier_iceflower";
	global.__objectNames[465] = "obj_modifier_iceflower_alt";
	global.__objectNames[466] = "obj_modifier_star";
	global.__objectNames[467] = "obj_modifier_1up";
	global.__objectNames[468] = "obj_modifier_poison";
	global.__objectNames[469] = "obj_modifier_watermelon_fire";
	global.__objectNames[470] = "obj_modifier_watermelon_ice";
	global.__objectNames[471] = "obj_modifier_watermelon_bomb";
	global.__objectNames[472] = "obj_modifier_coin_star";
	global.__objectNames[473] = "obj_modifier_coin_multi";
	global.__objectNames[474] = "obj_modifier_coin_multi_shroom";
	global.__objectNames[475] = "obj_modifier_coin_snake";
	global.__objectNames[476] = "obj_modifier_belt_right";
	global.__objectNames[477] = "obj_modifier_belt_right_fast";
	global.__objectNames[478] = "obj_modifier_belt_left";
	global.__objectNames[479] = "obj_modifier_belt_left_fast";
	global.__objectNames[480] = "obj_modifier_pswitch";
	global.__objectNames[481] = "obj_modifier_gswitch";
	global.__objectNames[482] = "obj_modifier_trampoline";
	global.__objectNames[483] = "obj_modifier_powblock";
	global.__objectNames[484] = "obj_modifier_detonator";
	global.__objectNames[485] = "obj_modifier_beanstalk";
	global.__objectNames[486] = "obj_modifier_key";
	global.__objectNames[487] = "obj_soundparent";
	global.__objectNames[488] = "obj_sound_oink_b";
	global.__objectNames[489] = "obj_sound_oink";
	global.__objectNames[490] = "obj_door";
	global.__objectNames[491] = "obj_door_s";
	global.__objectNames[492] = "obj_door_p";
	global.__objectNames[493] = "obj_door_boss";
	global.__objectNames[494] = "obj_warptop_branch";
	global.__objectNames[495] = "obj_warpbottom_branch";
	global.__objectNames[496] = "obj_warpleft_branch";
	global.__objectNames[497] = "obj_warpright_branch";
	global.__objectNames[498] = "obj_warptop";
	global.__objectNames[499] = "obj_warpbottom";
	global.__objectNames[500] = "obj_warpleft";
	global.__objectNames[501] = "obj_warpright";
	global.__objectNames[502] = "obj_warpnode";
	global.__objectNames[503] = "obj_warpparent";
	global.__objectNames[504] = "obj_followme";
	global.__objectNames[505] = "obj_playerparent";
	global.__objectNames[506] = "obj_holdparent";
	global.__objectNames[507] = "obj_holdparent_enemy";
	global.__objectNames[508] = "obj_enemyparent";
	global.__objectNames[509] = "obj_deactenemyparent";
	global.__objectNames[510] = "obj_bossparent";
	global.__objectNames[511] = "obj_solidenemyparent";
	global.__objectNames[512] = "obj_killparent";
	global.__objectNames[513] = "obj_physicsparent";
	global.__objectNames[514] = "obj_powerupparent";
	global.__objectNames[515] = "obj_projectileparent";
	global.__objectNames[516] = "obj_slopeparent";
	global.__objectNames[517] = "obj_slopeparent_move";
	global.__objectNames[518] = "obj_slopeparent_ceiling";
	global.__objectNames[519] = "obj_solid_moving";
	global.__objectNames[520] = "obj_semisolid_moving";
	global.__objectNames[521] = "obj_conveyorparent";
	global.__objectNames[522] = "obj_escalatorparent";
	global.__objectNames[523] = "obj_blockparent";
	global.__objectNames[524] = "obj_modparent";
	global.__objectNames[525] = "obj_trackparent";
	global.__objectNames[526] = "obj_pathparent";
	global.__objectNames[527] = "obj_collisionparent";
	global.__objectNames[528] = "obj_effectsparent";
	global.__objectNames[529] = "obj_iceparent";
	global.__objectNames[530] = "obj_deactivateparent";
	global.__objectNames[531] = "obj_removeme";
	global.__objectNames[532] = "obj_mario";
	global.__objectNames[533] = "obj_luigi";
	global.__objectNames[534] = "obj_toad";
	global.__objectNames[535] = "obj_peach";
	global.__objectNames[536] = "obj_cape";
	global.__objectNames[537] = "obj_cape_fly";
	global.__objectNames[538] = "obj_player_transform";
	global.__objectNames[539] = "obj_player_dead";
	global.__objectNames[540] = "obj_player_clear";
	global.__objectNames[541] = "obj_player_door";
	global.__objectNames[542] = "obj_player_fortress";
	global.__objectNames[543] = "obj_player_wallrunning";
	global.__objectNames[544] = "obj_spinner";
	global.__objectNames[545] = "obj_boundary_top";
	global.__objectNames[546] = "obj_boundary_bottom";
	global.__objectNames[547] = "obj_qblock_scatter";
	global.__objectNames[548] = "obj_brick_flip_b";
	global.__objectNames[549] = "obj_brick_throw_th";
	global.__objectNames[550] = "obj_beanstalk";
	global.__objectNames[551] = "obj_blockcoin";
	global.__objectNames[552] = "obj_coinsnake";
	global.__objectNames[553] = "obj_guessblock";
	global.__objectNames[554] = "obj_egg";
	global.__objectNames[555] = "obj_egg_hatch";
	global.__objectNames[556] = "obj_yoshi";
	global.__objectNames[557] = "obj_yoshi_ice";
	global.__objectNames[558] = "obj_yoshi_fire";
	global.__objectNames[559] = "obj_yoshi_bomb";
	global.__objectNames[560] = "obj_stomp";
	global.__objectNames[561] = "obj_tongue";
	global.__objectNames[562] = "obj_feather_sprout";
	global.__objectNames[563] = "obj_fireball";
	global.__objectNames[564] = "obj_iceball";
	global.__objectNames[565] = "obj_invincibility";
	global.__objectNames[566] = "obj_powerup_sprout";
	global.__objectNames[567] = "obj_powerup_swap";
	global.__objectNames[568] = "obj_reserveitem";
	global.__objectNames[569] = "obj_goal_fade";
	global.__objectNames[570] = "obj_goal_curtain";
	global.__objectNames[571] = "obj_checkpoint_front";
	global.__objectNames[572] = "obj_goal_tape";
	global.__objectNames[573] = "obj_goal_gate_front";
	global.__objectNames[574] = "obj_platform_pulley_right";
	global.__objectNames[575] = "obj_platform_pulley_rope";
	global.__objectNames[576] = "obj_platform_ferris_chain";
	global.__objectNames[577] = "obj_platform_ferris_platform";
	global.__objectNames[578] = "obj_accordion_block";
	global.__objectNames[579] = "obj_donut_ticker";
	global.__objectNames[580] = "obj_engine_rope";
	global.__objectNames[581] = "obj_engine_blade";
	global.__objectNames[582] = "obj_boltlift_fall";
	global.__objectNames[583] = "obj_boltlift_top";
	global.__objectNames[584] = "obj_blocktrain_front";
	global.__objectNames[585] = "obj_blocktrain_back";
	global.__objectNames[586] = "obj_blocktrain_middle";
	global.__objectNames[587] = "obj_blocktrain_killer";
	global.__objectNames[588] = "obj_powblock_active";
	global.__objectNames[589] = "obj_powblock_killer";
	global.__objectNames[590] = "obj_icicle_shard";
	global.__objectNames[591] = "obj_lakitucloud_front";
	global.__objectNames[592] = "obj_coin_alt";
	global.__objectNames[593] = "obj_coin_silver";
	global.__objectNames[594] = "obj_coinchange";
	global.__objectNames[595] = "obj_explosion";
	global.__objectNames[596] = "obj_explosion_stars";
	global.__objectNames[597] = "obj_twister_bubble";
	global.__objectNames[598] = "obj_enemy_dead";
	global.__objectNames[599] = "obj_enemy_multidead";
	global.__objectNames[600] = "obj_enemy_stomped";
	global.__objectNames[601] = "obj_enemy_score";
	global.__objectNames[602] = "obj_enemy_frozen";
	global.__objectNames[603] = "obj_enemy_tick";
	global.__objectNames[604] = "obj_microgoomba";
	global.__objectNames[605] = "obj_galoomba_held";
	global.__objectNames[606] = "obj_hammerbro_hammer";
	global.__objectNames[607] = "obj_boomerangbro_boomerang";
	global.__objectNames[608] = "obj_firebro_fireball";
	global.__objectNames[609] = "obj_afhb_rider";
	global.__objectNames[610] = "obj_sumobro_flame";
	global.__objectNames[611] = "obj_sumobro_lightning";
	global.__objectNames[612] = "obj_football";
	global.__objectNames[613] = "obj_mudball";
	global.__objectNames[614] = "obj_baseball";
	global.__objectNames[615] = "obj_dinotorch_flame";
	global.__objectNames[616] = "obj_spike_ball";
	global.__objectNames[617] = "obj_spiny_thrown";
	global.__objectNames[618] = "obj_spiny_green";
	global.__objectNames[619] = "obj_plantfire";
	global.__objectNames[620] = "obj_plantfire2";
	global.__objectNames[621] = "obj_ptooie_ball";
	global.__objectNames[622] = "obj_ptooie_bubble";
	global.__objectNames[623] = "obj_blargg_jump";
	global.__objectNames[624] = "obj_busterpickup";
	global.__objectNames[625] = "obj_torpedoted";
	global.__objectNames[626] = "obj_huckitcrab_rock";
	global.__objectNames[627] = "obj_lakitubait";
	global.__objectNames[628] = "obj_monty_jump";
	global.__objectNames[629] = "obj_lotusball";
	global.__objectNames[630] = "obj_lotusball_homing";
	global.__objectNames[631] = "obj_wiggler_body";
	global.__objectNames[632] = "obj_firesnake_trail";
	global.__objectNames[633] = "obj_pokey_dead";
	global.__objectNames[634] = "obj_angrysun_movement";
	global.__objectNames[635] = "obj_crumblebones";
	global.__objectNames[636] = "obj_drybones_bone";
	global.__objectNames[637] = "obj_blastakoopa_bullet";
	global.__objectNames[638] = "obj_zappakoopa_beam";
	global.__objectNames[639] = "obj_zappakoopa_beameff";
	global.__objectNames[640] = "obj_zappakoopa_laser";
	global.__objectNames[641] = "obj_mechakoopa_held";
	global.__objectNames[642] = "obj_mechakoopa_debris";
	global.__objectNames[643] = "obj_skewerparent";
	global.__objectNames[644] = "obj_skewertrunk";
	global.__objectNames[645] = "obj_skewertrunk_down";
	global.__objectNames[646] = "obj_skewertrunk_left";
	global.__objectNames[647] = "obj_skewertrunk_right";
	global.__objectNames[648] = "obj_firebar_ball";
	global.__objectNames[649] = "obj_rotodisc_disc";
	global.__objectNames[650] = "obj_rotodisc_flower_disc";
	global.__objectNames[651] = "obj_rotodisc_trail";
	global.__objectNames[652] = "obj_ballnchain_ball";
	global.__objectNames[653] = "obj_ballnchain_chain";
	global.__objectNames[654] = "obj_magic";
	global.__objectNames[655] = "obj_bowserstatue_fire";
	global.__objectNames[656] = "obj_boo_trail";
	global.__objectNames[657] = "obj_booring_boo";
	global.__objectNames[658] = "obj_bulletbill";
	global.__objectNames[659] = "obj_missilebill";
	global.__objectNames[660] = "obj_banzaibill";
	global.__objectNames[661] = "obj_bullseyebanzai";
	global.__objectNames[662] = "obj_bobomb_held";
	global.__objectNames[663] = "obj_cannon_ball";
	global.__objectNames[664] = "obj_rockywrench_wrench";
	global.__objectNames[665] = "obj_cheepcheep_gen";
	global.__objectNames[666] = "obj_spinycheep";
	global.__objectNames[667] = "obj_spinycheep_swim";
	global.__objectNames[668] = "obj_dolphin_gen";
	global.__objectNames[669] = "obj_shell_kicked";
	global.__objectNames[670] = "obj_chomp";
	global.__objectNames[671] = "obj_chomp_chain";
	global.__objectNames[672] = "obj_enemybubble_respawn";
	global.__objectNames[673] = "obj_mapcloud";
	global.__objectNames[674] = "obj_mapopener";
	global.__objectNames[675] = "obj_mapplayer_switcher";
	global.__objectNames[676] = "obj_light_lava_top";
	global.__objectNames[677] = "obj_light_lava_bottom";
	global.__objectNames[678] = "obj_ring";
	global.__objectNames[679] = "obj_ring_pow";
	global.__objectNames[680] = "obj_light_rengine";
	global.__objectNames[681] = "obj_light_disco_gen";
	global.__objectNames[682] = "obj_score";
	global.__objectNames[683] = "obj_score_goal";
	global.__objectNames[684] = "obj_shard";
	global.__objectNames[685] = "obj_shard_switch";
	global.__objectNames[686] = "obj_blob";
	global.__objectNames[687] = "obj_bubble";
	global.__objectNames[688] = "obj_bubble_h";
	global.__objectNames[689] = "obj_cloud";
	global.__objectNames[690] = "obj_note";
	global.__objectNames[691] = "obj_rain";
	global.__objectNames[692] = "obj_shellthump";
	global.__objectNames[693] = "obj_smoke";
	global.__objectNames[694] = "obj_smoke_water";
	global.__objectNames[695] = "obj_snow";
	global.__objectNames[696] = "obj_sparkle";
	global.__objectNames[697] = "obj_spinsmoke";
	global.__objectNames[698] = "obj_spinstar";
	global.__objectNames[699] = "obj_spinthump";
	global.__objectNames[700] = "obj_castledoor";
	global.__objectNames[701] = "obj_castledoor_black";
	global.__objectNames[702] = "obj_dialog";
	global.__objectNames[703] = "obj_message";
	global.__objectNames[704] = "obj_save";
	global.__objectNames[705] = "obj_credits";
	global.__objectNames[706] = "obj_title_menu_key";
	global.__objectNames[707] = "obj_title";
	global.__objectNames[708] = "obj_title_player";
	global.__objectNames[709] = "obj_audio_loop_sound";
	global.__objectNames[710] = "obj_fish";
	global.__objectNames[711] = "obj_hud";
	global.__objectNames[712] = "obj_hud_map";
	global.__objectNames[713] = "obj_pause";
	global.__objectNames[714] = "obj_blockbumper";
	global.__objectNames[715] = "obj_lightningsheet";
	global.__objectNames[716] = "obj_intro";
	global.__objectNames[717] = "obj_npc";
	global.__objectNames[718] = "obj_noyoshi_cutscene";
	global.__objectNames[719] = "obj_controller1";
	global.__objectNames[720] = "obj_mariostart";
	global.__objectNames[721] = "obj_gameover";
	global.__objectNames[722] = "obj_palaceswitch";
	global.__objectNames[723] = "obj_bonusblock_center";
	global.__objectNames[724] = "obj_bonusblock";
	global.__objectNames[725] = "obj_up";
	global.__objectNames[726] = "obj_down";
	global.__objectNames[727] = "obj_left";
	global.__objectNames[728] = "obj_right";
	global.__objectNames[729] = "obj_endmarker";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
